from enum import Enum
from datetime import datetime
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import Boolean, Integer, String, Text, DateTime, Enum as SAEnum, ForeignKey, func

from .base import BaseORM
from .user import UserORM


class NotificationTypeEnum(str, Enum):
    """
    Enum for notification types.

    - EXPORT_COMPLETED: An export job completed successfully.
    - EXPORT_FAILED: An export job finished with an error.
    """

    EXPORT_COMPLETED = "export_completed"
    EXPORT_FAILED = "export_failed"


class NotificationORM(BaseORM):
    """
    ORM for the Notification entity.
    Stores user-scoped notifications generated by background processes.
    """

    # Metadata
    __tablename__ = "notifications"

    # Columns
    id : Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id : Mapped[int] = mapped_column(ForeignKey(UserORM.id, ondelete="CASCADE"), index=True, nullable=False)
    type : Mapped[NotificationTypeEnum] = mapped_column(SAEnum(NotificationTypeEnum), nullable=False, index=True)
    title : Mapped[str] = mapped_column(String(255), nullable=False)
    message : Mapped[str] = mapped_column(Text, nullable=False)
    is_read : Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    created_at : Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    read_at : Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    entity_id : Mapped[int | None] = mapped_column(Integer, nullable=True)
    user : Mapped[UserORM] = relationship()
